package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1



/**
 * ContactId generated by hbm2java
 */
public class ContactId  implements java.io.Serializable {


     private int contactid;
     private int providerid;

    public ContactId() {
    }

    public ContactId(int contactid, int providerid) {
       this.contactid = contactid;
       this.providerid = providerid;
    }
   
    public int getContactid() {
        return this.contactid;
    }
    
    public void setContactid(int contactid) {
        this.contactid = contactid;
    }
    public int getProviderid() {
        return this.providerid;
    }
    
    public void setProviderid(int providerid) {
        this.providerid = providerid;
    }




}


