package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private ContactId id;
     private Provider provider;
     private String contactname;
     private int contactstate;
     private String phone;
     private Set orderMasters = new HashSet(0);

    public Contact() {
    }

	
    public Contact(ContactId id, Provider provider, int contactstate) {
        this.id = id;
        this.provider = provider;
        this.contactstate = contactstate;
    }
    public Contact(ContactId id, Provider provider, String contactname, int contactstate, String phone, Set orderMasters) {
       this.id = id;
       this.provider = provider;
       this.contactname = contactname;
       this.contactstate = contactstate;
       this.phone = phone;
       this.orderMasters = orderMasters;
    }
   
    public ContactId getId() {
        return this.id;
    }
    
    public void setId(ContactId id) {
        this.id = id;
    }
    public Provider getProvider() {
        return this.provider;
    }
    
    public void setProvider(Provider provider) {
        this.provider = provider;
    }
    public String getContactname() {
        return this.contactname;
    }
    
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }
    public int getContactstate() {
        return this.contactstate;
    }
    
    public void setContactstate(int contactstate) {
        this.contactstate = contactstate;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }




}


