package com.oc.model;
// Generated 09-22-2018 03:02:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int menuId;
     private String menuName;
     private Set subMenus = new HashSet(0);

    public Menu() {
    }

	
    public Menu(int menuId, String menuName) {
        this.menuId = menuId;
        this.menuName = menuName;
    }
    public Menu(int menuId, String menuName, Set subMenus) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.subMenus = subMenus;
    }
   
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public Set getSubMenus() {
        return this.subMenus;
    }
    
    public void setSubMenus(Set subMenus) {
        this.subMenus = subMenus;
    }




}


