package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private OrderMaster orderMaster;
     private Product product;
     private Float orderdetailquantity;
     private Float orderdetailtotal;
     private Float orderdetailunitprice;
     private String productColor;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, OrderMaster orderMaster, Product product) {
        this.id = id;
        this.orderMaster = orderMaster;
        this.product = product;
    }
    public OrderDetail(OrderDetailId id, OrderMaster orderMaster, Product product, Float orderdetailquantity, Float orderdetailtotal, Float orderdetailunitprice, String productColor) {
       this.id = id;
       this.orderMaster = orderMaster;
       this.product = product;
       this.orderdetailquantity = orderdetailquantity;
       this.orderdetailtotal = orderdetailtotal;
       this.orderdetailunitprice = orderdetailunitprice;
       this.productColor = productColor;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public OrderMaster getOrderMaster() {
        return this.orderMaster;
    }
    
    public void setOrderMaster(OrderMaster orderMaster) {
        this.orderMaster = orderMaster;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Float getOrderdetailquantity() {
        return this.orderdetailquantity;
    }
    
    public void setOrderdetailquantity(Float orderdetailquantity) {
        this.orderdetailquantity = orderdetailquantity;
    }
    public Float getOrderdetailtotal() {
        return this.orderdetailtotal;
    }
    
    public void setOrderdetailtotal(Float orderdetailtotal) {
        this.orderdetailtotal = orderdetailtotal;
    }
    public Float getOrderdetailunitprice() {
        return this.orderdetailunitprice;
    }
    
    public void setOrderdetailunitprice(Float orderdetailunitprice) {
        this.orderdetailunitprice = orderdetailunitprice;
    }
    public String getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }




}


