package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String productid;
     private String productname;
     private Integer productstate;
     private Float productprice;
     private Set orderDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(String productid) {
        this.productid = productid;
    }
    public Product(String productid, String productname, Integer productstate, Float productprice, Set orderDetails) {
       this.productid = productid;
       this.productname = productname;
       this.productstate = productstate;
       this.productprice = productprice;
       this.orderDetails = orderDetails;
    }
   
    public String getProductid() {
        return this.productid;
    }
    
    public void setProductid(String productid) {
        this.productid = productid;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public Integer getProductstate() {
        return this.productstate;
    }
    
    public void setProductstate(Integer productstate) {
        this.productstate = productstate;
    }
    public Float getProductprice() {
        return this.productprice;
    }
    
    public void setProductprice(Float productprice) {
        this.productprice = productprice;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


