package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provider generated by hbm2java
 */
public class Provider  implements java.io.Serializable {


     private int providerid;
     private String providername;
     private int providerstate;
     private Set contacts = new HashSet(0);

    public Provider() {
    }

	
    public Provider(int providerstate) {
        this.providerstate = providerstate;
    }
    public Provider(String providername, int providerstate, Set contacts) {
       this.providername = providername;
       this.providerstate = providerstate;
       this.contacts = contacts;
    }
   
    public int getProviderid() {
        return this.providerid;
    }
    
    public void setProviderid(int providerid) {
        this.providerid = providerid;
    }
    public String getProvidername() {
        return this.providername;
    }
    
    public void setProvidername(String providername) {
        this.providername = providername;
    }
    public int getProviderstate() {
        return this.providerstate;
    }
    
    public void setProviderstate(int providerstate) {
        this.providerstate = providerstate;
    }
    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }




}


