package com.oc.model;
// Generated 08-29-2018 02:13:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seller generated by hbm2java
 */
public class Seller  implements java.io.Serializable {


     private int sellerid;
     private String sellername;
     private int sellerstate;
     private Set orderMasters = new HashSet(0);

    public Seller() {
    }

	
    public Seller(int sellerstate) {
        this.sellerstate = sellerstate;
    }
    public Seller(String sellername, int sellerstate, Set orderMasters) {
       this.sellername = sellername;
       this.sellerstate = sellerstate;
       this.orderMasters = orderMasters;
    }
   
    public int getSellerid() {
        return this.sellerid;
    }
    
    public void setSellerid(int sellerid) {
        this.sellerid = sellerid;
    }
    public String getSellername() {
        return this.sellername;
    }
    
    public void setSellername(String sellername) {
        this.sellername = sellername;
    }
    public int getSellerstate() {
        return this.sellerstate;
    }
    
    public void setSellerstate(int sellerstate) {
        this.sellerstate = sellerstate;
    }
    public Set getOrderMasters() {
        return this.orderMasters;
    }
    
    public void setOrderMasters(Set orderMasters) {
        this.orderMasters = orderMasters;
    }




}


