package com.oc.model;
// Generated 09-22-2018 03:02:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubMenu generated by hbm2java
 */
public class SubMenu  implements java.io.Serializable {


     private int summenuId;
     private Menu menu;
     private String submenuName;
     private String url;
     private Set rollSubmenus = new HashSet(0);

    public SubMenu() {
    }

	
    public SubMenu(int summenuId, String submenuName, String url) {
        this.summenuId = summenuId;
        this.submenuName = submenuName;
        this.url = url;
    }
    public SubMenu(int summenuId, Menu menu, String submenuName, String url, Set rollSubmenus) {
       this.summenuId = summenuId;
       this.menu = menu;
       this.submenuName = submenuName;
       this.url = url;
       this.rollSubmenus = rollSubmenus;
    }
   
    public int getSummenuId() {
        return this.summenuId;
    }
    
    public void setSummenuId(int summenuId) {
        this.summenuId = summenuId;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getSubmenuName() {
        return this.submenuName;
    }
    
    public void setSubmenuName(String submenuName) {
        this.submenuName = submenuName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getRollSubmenus() {
        return this.rollSubmenus;
    }
    
    public void setRollSubmenus(Set rollSubmenus) {
        this.rollSubmenus = rollSubmenus;
    }




}


